# NUMPY All Methods - Exercises

In [1]:
# Created by Alejandro O. Rizzuto

## Import Numpy

In [2]:
import numpy as np

## Data types

In [3]:
np.array([0,3,10],dtype=np.bool_)

array([False,  True,  True])

In [4]:
np.array([0,-3,10.3],dtype=np.byte) # Convert float to int

array([ 0, -3, 10], dtype=int8)

In [5]:
np.array([0,-3,10],dtype=np.ubyte) # Overflow

array([  0, 253,  10], dtype=uint8)

In [6]:
np.array([0,-3.5,10],dtype=np.short) # Convert to int16

array([ 0, -3, 10], dtype=int16)

In [7]:
np.array([0,-3.5,10],dtype=np.intc) # Convert to int32

array([ 0, -3, 10], dtype=int32)

In [8]:
np.array([0,-3.5,10],dtype=np.uintc) # Overflow 

array([         0, 4294967293,         10], dtype=uint32)

In [9]:
np.array([0,-3.5,10],dtype=np.int_) # Convert to int

array([ 0, -3, 10])

In [10]:
np.array([0,-3.5,10],dtype=np.uint) # Overflow

array([         0, 4294967293,         10], dtype=uint32)

In [11]:
np.array([0,-3.5,10],dtype=np.longlong) # Convert to int64

array([ 0, -3, 10], dtype=int64)

In [12]:
np.array([0,-3.5,10],dtype=np.ulonglong) # Overflow. Convert to uint64

array([                   0, 18446744073709551613,                   10],
      dtype=uint64)

In [13]:
np.array([0,-3.5,10],dtype=np.half) # Convert to float16

array([ 0. , -3.5, 10. ], dtype=float16)

In [14]:
np.array([0,-3.5,10],dtype=np.single) # Convert to float32

array([ 0. , -3.5, 10. ], dtype=float32)

In [15]:
np.array([0,-3.5,10],dtype=np.double) # Convert to float

array([ 0. , -3.5, 10. ])

In [16]:
np.array([0,-3.5,10],dtype=np.longdouble) # Convert to float64

array([ 0. , -3.5, 10. ], dtype=float64)

In [17]:
np.array([0,-3.5,10],dtype=np.cdouble) # Convert to complex type

array([ 0. +0.j, -3.5+0.j, 10. +0.j])

In [18]:
np.array([0,-3.5,10],dtype=np.clongdouble) # Convert to complex128

array([ 0. +0.j, -3.5+0.j, 10. +0.j], dtype=complex128)

## Array Creation

### One dimension array

In [19]:
arr1=np.array([1,2,3,4])

In [20]:
arr1

array([1, 2, 3, 4])

### Two dimension array

In [21]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Mix of list and tuples

In [23]:
arr3=np.array([[1,2,3],(3,2,1)])

In [24]:
arr3

array([[1, 2, 3],
       [3, 2, 1]])

### Array of zeros

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

### Method "arange"

In [27]:
# Create a range of numbers

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [30]:
np.arange(3,5,0.2)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

### Method "linspace"

In [31]:
# Create a linear separation between number

In [32]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.linspace(10,50,7)

array([10.        , 16.66666667, 23.33333333, 30.        , 36.66666667,
       43.33333333, 50.        ])

### Method "indices"

In [34]:
#

In [35]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Importing data with genfromtxt

In [36]:
from io import StringIO

In [37]:
data=u"10,20,25\n40,50,64"

In [38]:
np.genfromtxt(StringIO(data), delimiter=",")

array([[10., 20., 25.],
       [40., 50., 64.]])

In [39]:
data = u"  1  2  3\n  4  5 67\n890123  4"

In [40]:
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [41]:
data = u"123456789\n   4  7 9\n   4567 9"

In [42]:
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

#### genfromtxt - Autostrip: Remove spaces

In [43]:
data = u"1, abc , 2\n 3, xxx, 4"

In [44]:
# Without autostrip

In [45]:
np.genfromtxt(StringIO(data), delimiter=",", dtype="|U5")

array([['1', ' abc ', ' 2'],
       ['3', ' xxx', ' 4']], dtype='<U5')

In [46]:
# With autostrip

In [47]:
np.genfromtxt(StringIO(data), delimiter=",", dtype="|U5", autostrip=True)

array([['1', 'abc', '2'],
       ['3', 'xxx', '4']], dtype='<U5')

In [48]:
data = u"""#
... # Skip me !
... 3, 4
... 5, 6 #This is the third line of the data
... 7, 8
... # And here comes the last line
... 9, 0
... """

In [49]:
np.genfromtxt(StringIO(data), comments="#", delimiter=",")

array([[3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

#### genfromtxt - Skip_header | Skip_footer

In [50]:
data = u"\n".join(str(i) for i in range(10))

In [51]:
data

'0\n1\n2\n3\n4\n5\n6\n7\n8\n9'

In [52]:
np.genfromtxt(StringIO(data),skip_header=3, skip_footer=5)

array([3., 4.])

#### genfromtxt - Usecols parameter

In [53]:
data = u"1 2 3 4\n5 6 7 8"

In [54]:
np.genfromtxt(StringIO(data), usecols=(0, -1)) # Use first and last columns

array([[1., 4.],
       [5., 8.]])

In [55]:
np.genfromtxt(StringIO(data),names="a,b,c,d", usecols=("a","d"))

array([(1., 4.), (5., 8.)], dtype=[('a', '<f8'), ('d', '<f8')])

In [56]:
np.genfromtxt(StringIO(data),names="a,b,c,d", usecols=("a,d"))

array([(1., 4.), (5., 8.)], dtype=[('a', '<f8'), ('d', '<f8')])

#### genfromtxt - Names argument: Add Names to columns

In [57]:
data = StringIO(u"1 2 3 4\n5 6 7 8")

In [58]:
np.genfromtxt(data, dtype=[(_, int) for _ in "abcd"])

array([(1, 2, 3, 4), (5, 6, 7, 8)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4'), ('d', '<i4')])

In [59]:
data = StringIO(u"1 2 3 4\n5 6 7 8")

In [60]:
np.genfromtxt(data, names="A, B, C, D")

array([(1., 2., 3., 4.), (5., 6., 7., 8.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8'), ('D', '<f8')])

In [61]:
data = StringIO("""So it goes\n
... #fst snd trd\n
... 1 2 3\n
... 4 5 6""")

In [62]:
np.genfromtxt(data, skip_header=1, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('fst', '<f8'), ('snd', '<f8'), ('trd', '<f8')])

In [63]:
data = StringIO("1 2 3\n 4 5 6")

In [64]:
ndtype=[('a',int), ('b', float), ('c', int)]

In [65]:
names = ["first", "second", "third"]

In [66]:
np.genfromtxt(data, names=names, dtype=ndtype)

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('first', '<i4'), ('second', '<f8'), ('third', '<i4')])

#### genfromtxt - defaultfmt argument

In [67]:
# If names=None, Numpy default is "f%i"

In [68]:
data = StringIO("1 2 0\n 4 5 True")

In [69]:
np.genfromtxt(data, dtype=(int, float, bool))

array([(1, 2., False), (4, 5.,  True)],
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '?')])

In [70]:
data = StringIO("1 2 3\n 4 5 6")

In [71]:
np.genfromtxt(data, dtype=(int, float, int), defaultfmt="var_%02i")

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_00', '<i4'), ('var_01', '<f8'), ('var_02', '<i4')])

## Shape

In [72]:
x=np.arange(36)

In [73]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [74]:
x.shape=(6,6)

In [75]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
x.shape=(3,12)

In [77]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [78]:
#x.shape=(2,4) # Error. No se puede crear una matriz de 2x4 con los datos de x

In [79]:
x.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

## Indexing

### Single element

In [80]:
x=np.arange(10)

In [81]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
x[2]

2

In [83]:
x[-3]

7

In [84]:
x.shape = (2,5)

In [85]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
x[1,3]

8

In [87]:
x[0,-1]

4

In [88]:
x[0]

array([0, 1, 2, 3, 4])

In [89]:
x[0,2:4]

array([2, 3])

In [90]:
x=np.arange(10)

In [91]:
x[2:5]

array([2, 3, 4])

In [92]:
x[:-7]

array([0, 1, 2])

In [93]:
x[1:7:2] # From 1 to 6 by 2

array([1, 3, 5])

In [94]:
x2=x.copy()

In [95]:
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Indexing Multi-dimensional arrays

In [96]:
y = np.arange(35).reshape(5,7)

In [97]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [98]:
y[np.array([0,2,4]), np.array([0,1,2])] # y[rows,columns]

array([ 0, 15, 30])

In [99]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [100]:
y[y>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [101]:
y>20

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [102]:
y[:,5]

array([ 5, 12, 19, 26, 33])

In [103]:
x = np.arange(30).reshape(2,3,5)

In [104]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [105]:
b = np.array([[True, True, False], [False, True, True]])

In [106]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Structural indexing tools

In [107]:
y = np.arange(35)

In [108]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [109]:
y.shape

(35,)

In [110]:
y=y.reshape(5,7)

In [111]:
y.shape

(5, 7)

In [112]:
y[:,np.newaxis,:]

array([[[ 0,  1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34]]])

In [113]:
z = np.arange(81).reshape(3,3,3,3)

In [114]:
z[1,...,2] # Equivalent to z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

### Assigning values to indexed arrays

In [115]:
x = np.arange(10)

In [116]:
x[2:7] = 1

In [117]:
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [118]:
x[2:7] = np.arange(5)

In [119]:
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

### Dealing with variable numbers of indices within programs

In [120]:
z = np.arange(81).reshape(3,3,3,3)

In [121]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [122]:
indices = (1,1,1,1)

In [123]:
z[indices]

40

In [124]:
indices = (1,...,1)

In [125]:
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

## Broadcasting

In [126]:
# How numpy treats arrays with different shapes during arithmetic operations

In [127]:
a = np.array([1.0, 2.0, 3.0])

In [128]:
b = np.array([2.0, 2.0, 2.0])

In [129]:
a * b # Element * Element

array([2., 4., 6.])

In [130]:
b=2

In [131]:
a*b # Element * Escalar

array([2., 4., 6.])

In [132]:
b=np.array([1,2])

In [133]:
#a*b # Error because a and b doesn't have same dimensions

In [134]:
a=np.array([8,1,6,1])

In [135]:
b=np.array([7,1,5])

In [136]:
#

In [137]:
x=np.arange(4)

In [138]:
xx=x.reshape(4,1)

In [139]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [140]:
x

array([0, 1, 2, 3])

In [141]:
y=np.ones(5)

In [142]:
z=np.ones((3,4))

In [143]:
x.shape

(4,)

In [144]:
y.shape

(5,)

In [145]:
y

array([1., 1., 1., 1., 1.])

In [146]:
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [147]:
xx*y

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

### Byte-swapping (ndarray)

In [148]:
# The ndarray is an object that provide a python array interface to data in memory

In [149]:
big_end_buffer = bytearray([2,4,5,2])

In [150]:
big_end_buffer

bytearray(b'\x02\x04\x05\x02')

In [151]:
# We migth want to use an ndarray to access these integers

In [152]:
# >: Big-endian - <: little-endian - i2=16bits

In [153]:
big_end_arr = np.ndarray(shape=(2,),dtype='>i2', buffer=big_end_buffer)

In [154]:
big_end_arr

array([ 516, 1282], dtype=int16)

In [155]:
[(2*256 + 4),(5*256+2)]

[516, 1282]

### Data and dtype endianness don’t match, change dtype to match data

In [156]:
wrong_end_dtype_arr = np.ndarray(shape=(2,),dtype='<i2', buffer=big_end_buffer)

In [157]:
wrong_end_dtype_arr[0] # Wrong

1026

In [158]:
fixed_end_dtype_arr = wrong_end_dtype_arr.newbyteorder()

In [159]:
fixed_end_dtype_arr[0]

516

In [160]:
fixed_end_dtype_arr.tobytes() == big_end_buffer # Not change in memory

True

### Structured arrays

In [165]:
# Structured arrays are ndarrays whose datatype is a composition of simpler datatypes organized as a sequence of named fields

In [166]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [167]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [168]:
x[1]

('Fido', 3, 27.)

In [169]:
x['age']

array([9, 3])

In [170]:
x['name']

array(['Rex', 'Fido'], dtype='<U10')

In [171]:
x['weight']

array([81., 27.], dtype=float32)

In [172]:
x['weight'][0]

81.0

### Structured Datatypes

#### A list of tuples

In [173]:
np.dtype([('x', 'f4'), ('y', np.float32), ('z', 'f4', (2, 2))])

dtype([('x', '<f4'), ('y', '<f4'), ('z', '<f4', (2, 2))])

In [174]:
np.dtype([('x', 'f4'), ('', 'i4'), ('z', 'i8')]) # fieldname empty

dtype([('x', '<f4'), ('f1', '<i4'), ('z', '<i8')])

#### A string of comma-separated

In [175]:
np.dtype('i8, f4, S3')

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [176]:
np.dtype('3int8, float32, (2, 3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

In [177]:
np.dtype('12int8, 24float32, (21,3,5,14)float64')

dtype([('f0', 'i1', (12,)), ('f1', '<f4', (24,)), ('f2', '<f8', (21, 3, 5, 14))])

#### A dictionary of field parameter arrays

In [178]:
np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

#### A dictionary of field names

In [179]:
np.dtype({'col1': ('i1', 0), 'col2': ('f4', 1)})

dtype([('col1', 'i1'), ('col2', '<f4')])

### Manipulating and Displaying Structured Datatypes

In [180]:
d = np.dtype([('x', 'i8'), ('y', 'f4')])

In [181]:
d.names

('x', 'y')

In [182]:
d.fields

mappingproxy({'x': (dtype('int64'), 0), 'y': (dtype('float32'), 8)})

In [183]:
x = np.array([(9, 81.0), (3, 27.0)],dtype=d) # Assign previous dtype

In [184]:
x

array([(9, 81.), (3, 27.)], dtype=[('x', '<i8'), ('y', '<f4')])

### Automatic Byte Offsets and Alignment

In [201]:
d=np.dtype('u1, u1, i4, f4, i8, u2',align=False)

In [202]:
d.names

('f0', 'f1', 'f2', 'f3', 'f4', 'f5')

In [203]:
print("offsets:", [d.fields[name][1] for name in d.names])

offsets: [0, 1, 2, 6, 10, 18]


In [205]:
print("Space in mem:", d.itemsize)

Space in mem: 20


### Field Titles

In [206]:
np.dtype([(('my title', 'name'), 'f4')]) # 1st way

dtype([(('my title', 'name'), '<f4')])

In [207]:
np.dtype({'name': ('i4', 0, 'my title')}) # 2nd way

dtype([(('my title', 'name'), '<i4')])

## Assigning data to a Structured Array

#### Assignment from Python Native Types (Tuples)

In [208]:
x = np.array([(1, 2, 3), (4, 5, 6)], dtype='i8, f4, f8')

In [210]:
x[1] = (7, 8, 9) # Replacing (4,5,6)

In [211]:
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

#### Assignment from Scalars

In [212]:
x = np.zeros(2, dtype='i8, f4, ?, S1') # (0,0) but each one with 4 types

In [213]:
x

array([(0, 0., False, b''), (0, 0., False, b'')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [214]:
x[:] = 3 # Replacing all by 3

In [215]:
x

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [216]:
x[:] = np.arange(2) # (0,1) but each one with 4 types

In [217]:
x

array([(0, 0., False, b'0'), (1, 1.,  True, b'1')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [219]:
twofield = np.zeros(2, dtype=[('A', 'i4'), ('B', 'i4')])

In [220]:
twofield

array([(0, 0), (0, 0)], dtype=[('A', '<i4'), ('B', '<i4')])

In [221]:
onefield = np.zeros(2, dtype=[('A', 'i4')])

In [222]:
onefield

array([(0,), (0,)], dtype=[('A', '<i4')])

In [223]:
nostruct = np.zeros(2, dtype='i4')

In [224]:
nostruct

array([0, 0])

#### Assignment from other Structured Arrays

In [229]:
a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c', 'S3')])

In [230]:
b = np.ones(3, dtype=[('x', 'f4'), ('y', 'S3'), ('z', 'O')])

In [231]:
b[:]=a

In [232]:
b

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

#### Accessing Individual Fields

In [233]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])

In [234]:
x['foo']

array([1, 3], dtype=int64)

In [235]:
x['foo'] = 10

In [236]:
x

array([(10, 2.), (10, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [237]:
y = x['bar']

In [238]:
y

array([2., 4.], dtype=float32)

In [239]:
y[:]=11

In [240]:
x

array([(10, 11.), (10, 11.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

#### Accessing Multiple Fields

In [241]:
a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])

In [243]:
a

array([(0, 0, 0.), (0, 0, 0.), (0, 0, 0.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [244]:
a[['a', 'c']]

array([(0, 0.), (0, 0.), (0, 0.)],
      dtype={'names':['a','c'], 'formats':['<i4','<f4'], 'offsets':[0,8], 'itemsize':12})

In [245]:
a[['a', 'c']] = (2, 3)

In [246]:
a

array([(2, 0, 3.), (2, 0, 3.), (2, 0, 3.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [247]:
a[['a', 'c']] = a[['c', 'a']]

In [248]:
a

array([(3, 0, 2.), (3, 0, 2.), (3, 0, 2.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

#### Structure Comparison

In [249]:
a = np.zeros(2, dtype=[('a', 'i4'), ('b', 'i4')])

In [250]:
b = np.ones(2, dtype=[('a', 'i4'), ('b', 'i4')])

In [251]:
a == b

array([False, False])

In [255]:
a = np.array([(0,1)])

In [256]:
b = np.array([(2,1)])

In [257]:
a == b

array([[False,  True]])

In [258]:
a = np.array([(0,1)], dtype=[('a', 'i4'), ('b', 'i4')])

In [259]:
b = np.array([(2,1)], dtype=[('a', 'i4'), ('b', 'f4')])

In [261]:
a['b'] == b['b']

array([ True])

### Record Arrays

In [268]:
recordarr = np.rec.array([(1, 2., 'Hello'), (2, 3., "World")],
...         dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])

In [269]:
recordarr.bar

array([2., 3.], dtype=float32)

In [270]:
recordarr[1:2]

rec.array([(2, 3., b'World')],
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [273]:
recordarr[1:2].foo # Idem recordarr.foo[1:2]

array([2])

In [274]:
recordarr[1].baz

b'World'

### Recarray Helper Functions

In [275]:
from numpy.lib import recfunctions as rfn

In [277]:
b = np.array([(1, 2, 5), (4, 5, 7), (7, 8 ,11), (10, 11, 12)],
...         dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'f8')])

In [278]:
rfn.apply_along_fields(np.mean, b) # Mean of each group

array([ 2.66666667,  5.33333333,  8.66666667, 11.        ])

In [279]:
rfn.apply_along_fields(np.mean, b[['x', 'z']]) # Mean of each group only for x,z

array([ 3. ,  5.5,  9. , 11. ])

In [280]:
#

In [282]:
a = np.array([(1, (2, 3.0)), (4, (5, 6.0))],
...  dtype=[('a', np.int64), ('b', [('ba', np.double), ('bb', np.int64)])])

In [283]:
rfn.drop_fields(a, 'a')

array([((2., 3),), ((5., 6),)],
      dtype=[('b', [('ba', '<f8'), ('bb', '<i8')])])

In [284]:
rfn.drop_fields(a, 'ba')

array([(1, (3,)), (4, (6,))], dtype=[('a', '<i8'), ('b', [('bb', '<i8')])])

In [285]:
rfn.drop_fields(a, ['ba', 'bb'])

array([(1,), (4,)], dtype=[('a', '<i8')])

In [286]:
#

In [287]:
from numpy.lib import recfunctions as rfn

In [288]:
ndtype =  np.dtype([('A', int),
...                 ('B', [('BA', int),
...                        ('BB', [('BBA', int), 
...                                ('BBB', int)])])])

In [289]:
rfn.get_fieldstructure(ndtype)

{'A': [],
 'B': [],
 'BA': ['B'],
 'BB': ['B'],
 'BBA': ['B', 'BB'],
 'BBB': ['B', 'BB']}

In [290]:
#

In [291]:
adtype = np.dtype([('a', int), ('b', [('ba', int), ('bb', int)])])

In [292]:
rfn.get_names(adtype)

('a', ('b', ('ba', 'bb')))

In [293]:
rfn.get_names_flat(adtype)

('a', 'b', 'ba', 'bb')

In [294]:
rfn.merge_arrays((np.array([1, 2]), np.array([10., 20., 30.])))

array([( 1, 10.), ( 2, 20.), (-1, 30.)],
      dtype=[('f0', '<i4'), ('f1', '<f8')])

In [295]:
rfn.merge_arrays((np.array([1, 2], dtype=np.int64),
...        np.array([10., 20., 30.])), usemask=False)

array([( 1, 10.), ( 2, 20.), (-1, 30.)],
      dtype=[('f0', '<i8'), ('f1', '<f8')])

In [296]:
a = np.array([(1, (2, [3.0, 30.])), (4, (5, [6.0, 60.]))],
  dtype=[('a', int),('b', [('ba', float), ('bb', (float, 2))])])

In [297]:
rfn.rename_fields(a, {'a':'A', 'bb':'BB'})

array([(1, (2., [ 3., 30.])), (4, (5., [ 6., 60.]))],
      dtype=[('A', '<i4'), ('b', [('ba', '<f8'), ('BB', '<f8', (2,))])])

In [298]:
from numpy.lib import recfunctions as rfn

In [300]:
def print_offsets(d):
    print("offsets:", [d.fields[name][1] for name in d.names])
    print("itemsize:", d.itemsize)

In [301]:
dt = np.dtype('u1, <i8, <f8', align=True)

In [302]:
dt

dtype({'names':['f0','f1','f2'], 'formats':['u1','<i8','<f8'], 'offsets':[0,8,16], 'itemsize':24}, align=True)

In [304]:
print_offsets(dt)

offsets: [0, 8, 16]
itemsize: 24


In [305]:
packed_dt = rfn.repack_fields(dt)

In [306]:
packed_dt

dtype([('f0', 'u1'), ('f1', '<i8'), ('f2', '<f8')])

In [307]:
print_offsets(packed_dt)

offsets: [0, 1, 9]
itemsize: 17


In [308]:
from numpy.lib import recfunctions as rfn

In [309]:
a = np.zeros(4, dtype=[('a', 'i4'), ('b', 'f4,u2'), ('c', 'f4', 2)])

In [310]:
a

array([(0, (0., 0), [0., 0.]), (0, (0., 0), [0., 0.]),
       (0, (0., 0), [0., 0.]), (0, (0., 0), [0., 0.])],
      dtype=[('a', '<i4'), ('b', [('f0', '<f4'), ('f1', '<u2')]), ('c', '<f4', (2,))])

In [311]:
rfn.structured_to_unstructured(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [313]:
dt = np.dtype([('a', 'i4'), ('b', 'f4,u2'), ('c', 'f4', 2)])

In [314]:
a = np.arange(20).reshape((4,5))

In [315]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [316]:
rfn.unstructured_to_structured(a, dt)

array([( 0, ( 1.,  2), [ 3.,  4.]), ( 5, ( 6.,  7), [ 8.,  9.]),
       (10, (11., 12), [13., 14.]), (15, (16., 17), [18., 19.])],
      dtype=[('a', '<i4'), ('b', [('f0', '<f4'), ('f1', '<u2')]), ('c', '<f4', (2,))])

### Writing custom array containers

In [318]:
import numpy as np

In [319]:
class DiagonalArray:
    def __init__(self, N, value):
        self._N = N
        self._i = value
    def __repr__(self):
        return f"{self.__class__.__name__}(N={self._N}, value={self._i})"
    def __array__(self):
        return self._i * np.eye(self._N)

In [320]:
arr = DiagonalArray(5, 1)

In [321]:
arr

DiagonalArray(N=5, value=1)

In [322]:
np.asarray(arr)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [323]:
np.multiply(arr, 2)

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

## Miscellaneous

In [324]:
myarr = np.array([1., 0., np.nan, 3.])

In [325]:
np.nonzero(myarr == np.nan)

(array([], dtype=int64),)

In [328]:
np.nan == myarr[2] # Always false

False

In [327]:
myarr

array([ 1.,  0., nan,  3.])

In [329]:
myarr[np.isnan(myarr)] = 0

In [330]:
myarr

array([1., 0., 0., 3.])

In [338]:
np.isinf(3)

False

In [339]:
np.isfinite(54)

True

In [340]:
arr=np.array([1,2,np.nan,4])

In [341]:
arr

array([ 1.,  2., nan,  4.])

In [342]:
np.nan_to_num(arr)

array([1., 2., 0., 4.])

In [343]:
arr

array([ 1.,  2., nan,  4.])

In [344]:
np.nansum(arr) # Nan exclude

7.0

In [345]:
np.sum(arr) # Nan not incluse -> gives error

nan

In [346]:
arr

array([ 1.,  2., nan,  4.])

In [347]:
np.nanmax(arr)

4.0

In [348]:
np.max(arr)

nan

In [349]:
np.nanmin(arr)

1.0

In [350]:
np.min(arr)

nan

In [351]:
np.nanargmax(arr) # Index of max

3

In [353]:
np.nanargmin(arr) # Index of min

0

### How numpy handles numerical exceptions

In [379]:
# The default is:
# 'warn' for invalid, divide, and overflow 
# 'ignore' for underflow

In [397]:
oldsettings=np.seterr()

In [376]:
np.zeros(5,dtype=np.float32)/0

<ipython-input-376-5b3bdc50b1af>:1: RuntimeWarning: invalid value encountered in true_divide
  np.zeros(5,dtype=np.float32)/0


array([nan, nan, nan, nan, nan], dtype=float32)

In [ ]:
# This can be changed: ignore,warn,raise,call,print,log
# Behaviors: all,invalid,divide,overflow,underflow

In [384]:
j = np.seterr(under='ignore')

In [385]:
j

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [387]:
np.array([1.e-100])**10

array([0.])

In [392]:
j = np.seterr(invalid='print')

In [393]:
def errorhandler(errstr, errflag):
...      print("saw stupid error!")

In [394]:
np.seterrcall(errorhandler)

<function __main__.errorhandler(errstr, errflag)>

In [395]:
j = np.seterr(all='call')

In [398]:
np.zeros(5, dtype=np.int32)/0

saw stupid error!


array([nan, nan, nan, nan, nan])

In [399]:
j = np.seterr(**oldsettings)

## Matlab / Numpy

In [414]:
import numpy as np

In [415]:
mat=np.matrix("[1 2 3;4 5 6]")

In [416]:
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [417]:
mat1=mat*2

In [418]:
mat1

matrix([[ 2,  4,  6],
        [ 8, 10, 12]])

In [419]:
mat2=np.matrix("[1 0 0;0 1 0]")

In [420]:
mat2 

matrix([[1, 0, 0],
        [0, 1, 0]])

In [423]:
mat1[:]

matrix([[ 2,  4,  6],
        [ 8, 10, 12]])

In [424]:
mat1[:,1]

matrix([[ 4],
        [10]])

In [425]:
mat1[1,2]

12

In [426]:
mat1>5

matrix([[False, False,  True],
        [ True,  True,  True]])

In [429]:
mat1.ndim

2

In [430]:
mat2.size

6

In [431]:
mat2.shape

(2, 3)

In [433]:
mat1.shape[1]

3

In [435]:
mat1[-1]

matrix([[ 8, 10, 12]])

In [436]:
mat2.T

matrix([[1, 0],
        [0, 1],
        [0, 0]])

In [437]:
mat1*mat2.T

matrix([[ 2,  4],
        [ 8, 10]])

In [441]:
np.isinf(mat1/mat2)

saw stupid error!


matrix([[False,  True,  True],
        [ True, False,  True]])

In [445]:
mat1

matrix([[ 2,  4,  6],
        [ 8, 10, 12]])

In [448]:
np.nonzero(mat1>4)

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [450]:
mat1[:1,(0,2)]=58

In [451]:
mat1

matrix([[58,  4, 58],
        [ 8, 10, 12]])

In [452]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [453]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [454]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [455]:
28*np.eye(4)

array([[28.,  0.,  0.,  0.],
       [ 0., 28.,  0.,  0.],
       [ 0.,  0., 28.,  0.],
       [ 0.,  0.,  0., 28.]])

In [457]:
np.diag(28*np.eye(4))

array([28., 28., 28., 28.])

In [459]:
np.random.rand(3,4)

array([[0.79271175, 0.81258864, 0.26190018, 0.04600955],
       [0.59158914, 0.5295742 , 0.10054592, 0.82282623],
       [0.58757829, 0.84622534, 0.31770276, 0.51400804]])

In [460]:
np.random.rand(5)

array([0.04025356, 0.48168577, 0.39488477, 0.76586798, 0.50043664])

In [461]:
np.random.rand()

0.015750263820357047

In [463]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [464]:
np.mgrid[0:2,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [467]:
np.mgrid[0:3,2:3]

array([[[0],
        [1],
        [2]],

       [[2],
        [2],
        [2]]])

In [468]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [471]:
np.tile(np.array([1,2]), (3, 2)) # tile(a, (m, n)): create m by n copies of a

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])

In [473]:
np.concatenate((mat1,mat2),1) # Concatenate columns

matrix([[58,  4, 58,  1,  0,  0],
        [ 8, 10, 12,  0,  1,  0]])

In [474]:
np.concatenate((mat1,mat2)) # Concatenate rows

matrix([[58,  4, 58],
        [ 8, 10, 12],
        [ 1,  0,  0],
        [ 0,  1,  0]])

In [477]:
mat1

matrix([[58,  4, 58],
        [ 8, 10, 12]])

In [475]:
mat1.max()

58

In [476]:
mat1.max(0) # Max row

matrix([[58, 10, 58]])

In [478]:
mat1.max(1) # Max column

matrix([[58],
        [12]])

In [479]:
np.maximum(mat1,mat2)

matrix([[58,  4, 58],
        [ 8, 10, 12]])

In [480]:
np.linalg.norm(np.array(3))

3.0