# NUMPY All Methods - Exercises

In [ ]:
# Created by Alejandro O. Rizzuto

## Import Numpy

In [1]:
import numpy as np

## Data types

In [19]:
np.array([0,3,10],dtype=np.bool_)

array([False,  True,  True])

In [24]:
np.array([0,-3,10.3],dtype=np.byte) # Convert float to int

array([ 0, -3, 10], dtype=int8)

In [22]:
np.array([0,-3,10],dtype=np.ubyte) # Overflow

array([  0, 253,  10], dtype=uint8)

In [27]:
np.array([0,-3.5,10],dtype=np.short) # Convert to int16

array([ 0, -3, 10], dtype=int16)

In [28]:
np.array([0,-3.5,10],dtype=np.intc) # Convert to int32

array([ 0, -3, 10], dtype=int32)

In [30]:
np.array([0,-3.5,10],dtype=np.uintc) # Overflow 

array([         0, 4294967293,         10], dtype=uint32)

In [31]:
np.array([0,-3.5,10],dtype=np.int_) # Convert to int

array([ 0, -3, 10])

In [32]:
np.array([0,-3.5,10],dtype=np.uint) # Overflow

array([         0, 4294967293,         10], dtype=uint32)

In [33]:
np.array([0,-3.5,10],dtype=np.longlong) # Convert to int64

array([ 0, -3, 10], dtype=int64)

In [36]:
np.array([0,-3.5,10],dtype=np.ulonglong) # Overflow. Convert to uint64

array([                   0, 18446744073709551613,                   10],
      dtype=uint64)

In [37]:
np.array([0,-3.5,10],dtype=np.half) # Convert to float16

array([ 0. , -3.5, 10. ], dtype=float16)

In [38]:
np.array([0,-3.5,10],dtype=np.single) # Convert to float32

array([ 0. , -3.5, 10. ], dtype=float32)

In [39]:
np.array([0,-3.5,10],dtype=np.double) # Convert to float

array([ 0. , -3.5, 10. ])

In [40]:
np.array([0,-3.5,10],dtype=np.longdouble) # Convert to float64

array([ 0. , -3.5, 10. ], dtype=float64)

In [41]:
np.array([0,-3.5,10],dtype=np.cdouble) # Convert to complex type

array([ 0. +0.j, -3.5+0.j, 10. +0.j])

In [42]:
np.array([0,-3.5,10],dtype=np.clongdouble) # Convert to complex128

array([ 0. +0.j, -3.5+0.j, 10. +0.j], dtype=complex128)

## Array Creation

### One dimension array

In [46]:
arr1=np.array([1,2,3,4])

In [50]:
arr1

array([1, 2, 3, 4])

### Two dimension array

In [48]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [49]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Mix of list and tuples

In [52]:
arr3=np.array([[1,2,3],(3,2,1)])

In [53]:
arr3

array([[1, 2, 3],
       [3, 2, 1]])

### Array of zeros

In [56]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

### Method "arange"

In [ ]:
# Create a range of numbers

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [61]:
np.arange(3,5,0.2)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

### Method "linspace"

In [ ]:
# Create a linear separation between number

In [63]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [65]:
np.linspace(10,50,7)

array([10.        , 16.66666667, 23.33333333, 30.        , 36.66666667,
       43.33333333, 50.        ])

### Method "indices"

In [ ]:
#

In [69]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Importing data with genfromtxt

In [70]:
from io import StringIO

In [71]:
data=u"10,20,25\n40,50,64"

In [74]:
np.genfromtxt(StringIO(data), delimiter=",")

array([[10., 20., 25.],
       [40., 50., 64.]])

In [75]:
data = u"  1  2  3\n  4  5 67\n890123  4"

In [76]:
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [77]:
data = u"123456789\n   4  7 9\n   4567 9"

In [78]:
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

#### genfromtxt - Autostrip: Remove spaces

In [86]:
data = u"1, abc , 2\n 3, xxx, 4"

In [107]:
# Without autostrip

In [82]:
np.genfromtxt(StringIO(data), delimiter=",", dtype="|U5")

array([['1', ' abc ', ' 2'],
       ['3', ' xxx', ' 4']], dtype='<U5')

In [108]:
# With autostrip

In [85]:
np.genfromtxt(StringIO(data), delimiter=",", dtype="|U5", autostrip=True)

array([['1', 'abc', '2'],
       ['3', 'xxx', '4']], dtype='<U5')

In [88]:
data = u"""#
... # Skip me !
... 3, 4
... 5, 6 #This is the third line of the data
... 7, 8
... # And here comes the last line
... 9, 0
... """

In [89]:
np.genfromtxt(StringIO(data), comments="#", delimiter=",")

array([[3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

#### genfromtxt - Skip_header | Skip_footer

In [98]:
data = u"\n".join(str(i) for i in range(10))

In [99]:
data

'0\n1\n2\n3\n4\n5\n6\n7\n8\n9'

In [100]:
np.genfromtxt(StringIO(data),skip_header=3, skip_footer=5)

array([3., 4.])

#### genfromtxt - Usecols parameter

In [102]:
data = u"1 2 3 4\n5 6 7 8"

In [103]:
np.genfromtxt(StringIO(data), usecols=(0, -1)) # Use first and last columns

array([[1., 4.],
       [5., 8.]])

In [104]:
np.genfromtxt(StringIO(data),names="a,b,c,d", usecols=("a","d"))

array([(1., 4.), (5., 8.)], dtype=[('a', '<f8'), ('d', '<f8')])

In [105]:
np.genfromtxt(StringIO(data),names="a,b,c,d", usecols=("a,d"))

array([(1., 4.), (5., 8.)], dtype=[('a', '<f8'), ('d', '<f8')])

#### genfromtxt - Names argument: Add Names to columns

In [120]:
data = StringIO(u"1 2 3 4\n5 6 7 8")

In [121]:
np.genfromtxt(data, dtype=[(_, int) for _ in "abcd"])

array([(1, 2, 3, 4), (5, 6, 7, 8)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4'), ('d', '<i4')])

In [118]:
np.genfromtxt(data, names="A, B, C, D")

array([(1., 2., 3., 4.), (5., 6., 7., 8.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8'), ('D', '<f8')])

In [129]:
data = StringIO("""So it goes\n
... #fst snd trd\n
... 1 2 3\n
... 4 5 6""")

In [130]:
np.genfromtxt(data, skip_header=1, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('fst', '<f8'), ('snd', '<f8'), ('trd', '<f8')])

In [138]:
data = StringIO("1 2 3\n 4 5 6")

In [139]:
ndtype=[('a',int), ('b', float), ('c', int)]

In [140]:
names = ["first", "second", "third"]

In [141]:
np.genfromtxt(data, names=names, dtype=ndtype)

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('first', '<i4'), ('second', '<f8'), ('third', '<i4')])

#### genfromtxt - defaultfmt argument

In [142]:
# If names=None, Numpy default is "f%i"

In [144]:
data = StringIO("1 2 0\n 4 5 True")

In [145]:
np.genfromtxt(data, dtype=(int, float, bool))

array([(1, 2., False), (4, 5.,  True)],
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '?')])

In [146]:
data = StringIO("1 2 3\n 4 5 6")

In [147]:
np.genfromtxt(data, dtype=(int, float, int), defaultfmt="var_%02i")

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_00', '<i4'), ('var_01', '<f8'), ('var_02', '<i4')])

#### genfromtxt - converters argument